"""
Django settings for config project.
Generated by 'django-admin startproject' using Django 6.0.
For more information, see https://docs.djangoproject.com/en/6.0/topics/settings/
"""

import environ
from pathlib import Path
from datetime import timedelta
from functools import partial

# Build paths inside the project like this: BASE_DIR / 'subdir'.
env = environ.Env()
environ.Env.read_env(Path(__file__).resolve().parent.parent.parent / '.env')  # .env à la root

BASE_DIR = Path(__file__).resolve().parent.parent.parent
APPS_DIR = BASE_DIR / "apps"

# Partial functions pour paths et timedeltas
static_path = partial(Path.joinpath, BASE_DIR)
media_path = partial(Path.joinpath, BASE_DIR)
jwt_timedelta = partial(timedelta)

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool('DEBUG', default=False)

ALLOWED_HOSTS = env.list('ALLOWED_HOSTS', default=[])

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third party apps
    'corsheaders',
    'rest_framework',
    'rest_framework_simplejwt',  # ← Ajouté pour JWT
    'django_filters',
    'anymail',
    'django_celery_beat',
    'django_celery_results',
    
    # Local apps
    'apps.utilisateur',
    'apps.products',
    'apps.orders',
    'apps.marketplace',
    'apps.dashboard',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_htmx.middleware.HtmxMiddleware',
]

ROOT_URLCONF = 'config.urls'

# Custom user model (de notre UML : Utilisateur avec rôles Client/Entreprise)
AUTH_USER_MODEL = 'utilisateur.Utilisateur'
LOGIN_REDIRECT_URL = '/dashboard/index'  # Après login
LOGOUT_REDIRECT_URL = '/marketplace/home/'  # Après logout
LOGIN_URL = '/login/' # cette route 

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',  # ← Corrigé : DjangoTemplates
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'apps.orders.context_processors.cart_count',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'

# Database (PostgreSQL avec options avancées)
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': env('DB_NAME'),
        'USER': env('DB_USER'),
        'PASSWORD': env('DB_PASSWORD'),
        'HOST': env('DB_HOST', default='localhost'),
        'PORT': env('DB_PORT', default='5432'),
        'OPTIONS': {
            'connect_timeout': 10,
            'sslmode': 'require' if env.bool('DB_SSL', default=False) else 'disable',
        },
        'CONN_MAX_AGE': env.int('DB_CONN_MAX_AGE', default=0),
        'CONN_HEALTH_CHECKS': True,  # Django 6.0 OK
    }
}

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# Internationalization (fr-fr pour agro FR, avec formats €/dates locales)
LANGUAGE_CODE = 'fr-fr'
TIME_ZONE = 'Europe/Paris'
USE_I18N = True
USE_TZ = True
USE_L10N = True

# Static files
STATIC_URL = '/static/'
STATIC_ROOT = static_path('staticfiles')
STATICFILES_DIRS = [
    APPS_DIR / "marketplace" / "static",
    APPS_DIR / "dashboard" / "static",
]

MEDIA_URL = '/media/'
MEDIA_ROOT = media_path('media')
DEFAULT_FILE_STORAGE = 'django.core.files.storage.FileSystemStorage'  # Fallback local

# REST Framework (avec search/ordering pour catalogue produits agro)
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': env.int('API_PAGE_SIZE', default=20),
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',  # Ex: search "tomates bio"
        'rest_framework.filters.OrderingFilter',
    ],
}

# JWT
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': jwt_timedelta(hours=6),
    'REFRESH_TOKEN_LIFETIME': jwt_timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
}

# Celery (broker Redis, tâche low-stock pour Products)
CELERY_BROKER_URL = env('CELERY_BROKER', default='redis://localhost:6379/0')
CELERY_RESULT_BACKEND = env('CELERY_BACKEND', default='redis://localhost:6379/0')
CELERY_ACCEPT_CONTENT = ['application/json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE
CELERY_BEAT_SCHEDULE = {
    'check-low-stock-every-hour': {
        'task': 'apps.products.tasks.check_low_stock',  # ← Corrigé path
        'schedule': jwt_timedelta(hours=1).total_seconds(),
    },
}
# Security settings (relâchés pour dev local)
CSRF_COOKIE_SECURE = False  # Pour HTTP local (pas HTTPS)
CSRF_COOKIE_HTTPONLY = False  # Permet JS access (si tu gardes le script)
CSRF_TRUSTED_ORIGINS = ['http://127.0.0.1:8000', 'http://localhost:8000']  # 


# Email (Anymail/SendGrid par défaut)
EMAIL_BACKEND = 'anymail.backends.sendgrid.EmailBackend'  # ← Corrigé : cohérent avec Anymail
ANYMAIL = {
    "SENDGRID_API_KEY": env('SENDGRID_KEY', default=''),
}
DEFAULT_FROM_EMAIL = env('DEFAULT_EMAIL', default='noreply@agrimarket.com')
SERVER_EMAIL = DEFAULT_FROM_EMAIL

# Email backend pour dev (affiche mails dans console)
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'  # Change en 'smtp' ou Anymail pour prod
DEFAULT_FROM_EMAIL = 'noreply@agribusiness.com'  # Expéditeur des mails reset

# Pour prod (ex: SendGrid, comme dans ton Anymail config)
# EMAIL_BACKEND = 'anymail.backends.sendgrid.EmailBackend'
# ANYMAIL = {"SENDGRID_API_KEY": env('SENDGRID_KEY')}

# URLs pour reset (optionnel, mais utile)
PASSWORD_RESET_TIMEOUT = 259200  # 