# Generated by Django 6.0 on 2025-12-13 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producerprofile',
            name='validated',
            field=models.BooleanField(default=False, verbose_name='Validé par admin'),
        ),
    ]
