# Generated by Django 6.0 on 2025-12-15 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0002_producerprofile_validated'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='last_password_change',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Dernier changement de mot de passe'),
        ),
    ]
