# Generated by Django 6.0 on 2025-12-27 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0004_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='producerprofile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='producer_profiles/', verbose_name='Image de profil'),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='user_profiles/', verbose_name='Image de profil'),
        ),
    ]
